---
elasticsearch_configs:
  dl_url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.3.0.rpm
  rpm_path: /usr/local/src/elasticsearch-6.3.0.rpm

jdk:
  dl_url: http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.rpm
  rpm_path: "/usr/local/src/jdk-8u121-linux-x64.rpm"
