---
- name: Get Inventory
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Refresh inventory
      meta: refresh_inventory

- name: EFK Instale
  hosts: tag_Role_cent_efk
  become: true
  roles:
    - jdk
    - elasticsearch

#    - td-agent
#    - limits
#    - kernel
#    - kibana
